#!/usr/bin/env zsh

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bun completions
[ -s "/home/mayant/.bun/_bun" ] && source "/home/mayant/.bun/_bun"

# LLVM
# export PATH="$PATH:$HOME/programs/llvm-17.0.6/bin"
# export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/programs/llvm-17.0.6/lib"

# Rust
. "$HOME/.cargo/env"

# fnm
export PATH="/home/mayant/.local/share/fnm:$PATH"
eval "`fnm env`"

