#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Convenience aliases
alias cls='clear'
alias gs='git status'
alias gl='git log --oneline'
alias ga='git add'
alias gco='git checkout'
alias gsu='git submodule update --recursive && git submodule sync --recursive'

# Since I primarily use Zsh in WSL, create an alias to open files with the default Windows app
# alias open='wslview'

# CMake aliases
alias cmc='cmake .. -GNinja'
alias cmb='cmake --build .'

# Friendship ended with GCC now clang is new best friend
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

# pip and other custom installed binaries
export PATH="$HOME/.local/bin":$PATH

# Disable PATH_DIRS on WSL, tab completion is slow otherwise https://github.com/sorin-ionescu/prezto/issues/1820
unsetopt PATH_DIRS

# For starship to work
setopt prompt_subst interactive_comments

# Haskell setup
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

