#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Convenience aliases
alias cls='clear'
alias gs='git status'
alias gl='git log --oneline'
alias ga='git add'
alias gco='git checkout'

# Since I primarily use Zsh in WSL, create an alias to open files with the default Windows app
alias open='wslview'

# CMake aliases
alias cmc='cmake .. -GNinja'
alias cmb='cmake --build .'

# Haskell setup
[ -f "/home/mayant/.ghcup/env" ] && source "/home/mayant/.ghcup/env" # ghcup-env

# Friendship ended with GCC now clang is new best friend
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

# pip installed binaries go here
export PATH="/home/mayant/.local/bin":$PATH

# CUDA install path
# export PATH="/usr/local/cuda-11.3/bin":$PATH

# NodeJS
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Disable PATH_DIRS on WSL, tab completion is slow otherwise https://github.com/sorin-ionescu/prezto/issues/1820
unsetopt PATH_DIRS

